trend_resolution_hz: 1
stream_rate_adjust_factor: 1
holds: true
number_of_trends: 4
column_ids: ["chrom_1", "chrom_2", "chrom_3", "chrom_4"]
batch_quality:
  chrom_1: ["good", "good", "good", "good"]
  chrom_2: ["good", "bad", "good", "good"]
  chrom_3: ["good", "good", "good", "bad"]
  chrom_4: ["good", "bad", "good", "good"]
noise_scale: 1.0
column_util_gap: 1000
noise_def:
  uv_mau: [0, 2.0]
  cond_mScm: [0, 0.15]
  ph: [0, 0.01]
  flow_mL_min: [0, 300]
  pressure_bar: [0, 0.01]